pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - status-success=ci/circleci
      - status-success=deploy/netlify
      - status-success=cla/google
      - "#approved-reviews-by>=1"
      - label!=do-not-merge
      - label!=do-not-merge/work-in-progress
      - label!=do-not-merge/hold
    actions:
      merge:
        method: squash
        strict: false

  - name: Automatically cherry pick a PR from master to the release-1.2 branch if the right label is set
    conditions:
      - base=master
      - label=action/merge-to-release-1.2-branch
    actions:
      backport:
        branches:
          - release-1.2

  - name: Automatically cherry pick a PR from master to the release-1.3 branch if the right label is set
    conditions:
      - base=master
      - label=action/merge-to-release-1.3-branch
    actions:
      backport:
        branches:
          - release-1.2

  - name: Automatically cherry pick a PR from the release branch to master if the right label is set
    conditions:
      - base~=release-?.?
      - label=action/merge-to-master
    actions:
      backport:
        branches:
          - master
