pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - status-success=ci/circleci
      - status-success=deploy/netlify
      - status-success=cla/google
      - "#approved-reviews-by>=1"
      - label!=do-not-merge
      - label!=do-not-merge/work-in-progress
      - label!=do-not-merge/hold
    actions:
      merge:
        method: squash
        strict: false
  - name: Automatically merge PRs from master to the release branch if the right label is set
    conditions:
      - base=master
      - label=action/merge-to-release-branch
    actions:
      - backport:
        - release-1.1
