diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=SYRForever
user.email=1655902181@qq.com
https.proxy=http://127.0.0.1:10808
http.proxy=http://127.0.0.1:10808
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/yanrongshi/istio.io.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.feat/add_zh_gateway.io.remote=origin
branch.feat/add_zh_gateway.io.merge=refs/heads/feat/add_zh_gateway.io
gui.wmstate=normal
gui.geometry=841x483+26+26 189 218
branch.add_zh_gateway_api.remote=origin
branch.add_zh_gateway_api.merge=refs/heads/add_zh_gateway_api
branch.feat/add_zh_gateway-api.remote=origin
branch.feat/add_zh_gateway-api.merge=refs/heads/feat/add_zh_gateway-api
