unrestricted_licenses:
  - Apache-2.0
  - ISC
  - AFL-2.1
  - AFL-3.0
  - Artistic-1.0
  - Artistic-2.0
  - Apache-1.1
  - BSD-1-Clause
  - BSD-2-Clause
  - BSD-3-Clause
  - FTL
  - LPL-1.02
  - MS-PL
  - MIT
  - NCSA
  - OpenSSL
  - PHP-3.0
  - TCP-wrappers
  - W3C
  - Xnet
  - Zlib

reciprocal_licenses:
  - CC0-1.0
  - APSL-2.0
  - CDDL-1.0
  - CDDL-1.1
  - CPL-1.0
  - EPL-1.0
  - IPL-1.0
  - MPL-1.0
  - MPL-1.1
  - MPL-2.0
  - Ruby

restricted_licenses:
  - GPL-1.0-only
  - GPL-1.0-or-later
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-3.0-only
  - GPL-3.0-or-later
  - LGPL-2.0-only
  - LGPL-2.0-or-later
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - NPL-1.0
  - NPL-1.1
  - OSL-1.0
  - OSL-1.1
  - OSL-2.0
  - OSL-2.1
  - OSL-3.0
  - QPL-1.0
  - Sleepycat

whitelisted_modules:
  - github.com/apache/thrift
  - github.com/ghodss/yaml
  - github.com/gogo/protobuf
  - github.com/inconshreveable/mousetrap
  - github.com/julienschmidt/httprouter
  - github.com/magiconair/properties
  - github.com/pmezard/go-difflib
  - github.com/russross/blackfriday
  - gopkg.in/check.v1
  - gopkg.in/tomb.v1
  - github.com/kr/logfmt
