---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: sds
  tag: 1.4.0
  hub: docker.io/istio  
...
